# Generated by Django 2.0.5 on 2018-06-16 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='crew',
            name='captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crews.Worker'),
        ),
        migrations.AddField(
            model_name='crew',
            name='workers',
            field=models.ManyToManyField(related_name='crews', to='crews.Worker'),
        ),
    ]
